spring:
  application:
    name: suunto-store
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/store?useSSL=false&useUnicode=true&allowMultiQueries=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456
    druid:
      initial-size: 3
      min-idle: 3
      max-active: 10
      max-wait: 60000
mybatis:
  mapper-locations: classpath:mybatis/*.xml
  type-aliases-package: com.study.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

apis:
  map:
    url: https://apis.map.qq.com
    key: 7BOBZ-AOVWS-YH6OS-6QTRR-YRIKH-P4BIT